spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: rajneesh
    password: Rajneesh2024
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#    shareskillotpservice@gmail.com
#    Rajneesh@2024
  mail:
    host: smtp.gmail.com
    port: 587
    username: shareskillotpservice@gmail.com
    password: nlbx jler jtfl ubqy
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
jwt:
  secretKey: "868jkhkkyiyiutyutyugnknkjbvghcqfdxdxabllhs;wop]jsojlslnafytqdr1d457t76gg,.lslknssanjwnwn"
